POST https://dx40q25lhd.execute-api.us-east-1.amazonaws.com/dev/v1/user

{
    "name": "Osusara",
    "age": 24
}
###
GET https://dx40q25lhd.execute-api.us-east-1.amazonaws.com/dev/v1/user

###
POST https://dx40q25lhd.execute-api.us-east-1.amazonaws.com/dev/v1/user/{name}

###
PUT https://dx40q25lhd.execute-api.us-east-1.amazonaws.com/dev/v1/user/{name}

###
DELETE https://dx40q25lhd.execute-api.us-east-1.amazonaws.com/dev/v1/user/{name}